name: mealty
description: "A Flutter project for my thesis."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^14.1.1
  google_fonts: ^6.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  material_design_icons_flutter: ^7.0.7296


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/