name: mealty
description: "A Flutter project for my thesis."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  provider: ^6.1.2
  location: ^6.0.2
  geocoding: ^3.0.0
  go_router: ^14.1.1
  geolocator: ^12.0.0
  photo_view: ^0.14.0
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.3.0
  material_design_icons_flutter: ^7.0.7296


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/